package:
  name: rider
  version: "1.0.0"

source:
  git_url: https://github.com/emblab-westlake/Rider.git
  git_rev: master   
build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - biopython
    - blast
    - hmmer
    - prodigal
    - diamond
    - entrez-direct
    - mmseqs2
    - foldseek
    - torch
    - transformers
    - scikit-learn

about:
  home: https://github.com/emblab-westlake/Rider
  license: MIT
  summary: "Rider: A tool for RNA Virus prediction"